services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: sgate-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: sgate_production
      POSTGRES_USER: sgate_prod
      POSTGRES_PASSWORD: ${DB_PASSWORD:-sgate_secure_password}
      POSTGRES_INITDB_ARGS: "--auth-local=trust --auth-host=md5"
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    ports:
      - "9020:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sgate_prod -d sgate_production"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - sgate-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: sgate-redis-prod
    restart: unless-stopped
    command: |
      sh -c '
      mkdir -p /usr/local/etc/redis &&
      echo "
      bind 0.0.0.0
      port 6379
      requirepass $$REDIS_PASSWORD
      maxmemory 512mb
      maxmemory-policy allkeys-lru
      save 900 1
      save 300 10
      save 60 10000
      loglevel notice
      protected-mode yes
      tcp-keepalive 300
      timeout 0
      " > /usr/local/etc/redis/redis.conf &&
      redis-server /usr/local/etc/redis/redis.conf
      '
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-redis_secure_password}
    volumes:
      - redis_data:/data
      - redis_logs:/var/log/redis
    ports:
      - "9021:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-redis_secure_password}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - sgate-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # API Service
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.simple.working
    image: sgate/api:${VERSION:-latest}
    container_name: sgate-api-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 4000
      DATABASE_URL: postgresql://sgate_prod:${DB_PASSWORD:-sgate_secure_password}@postgres:5432/sgate_production
      REDIS_URL: redis://default:${REDIS_PASSWORD:-redis_secure_password}@redis:6379
      API_KEY_SALT: ${API_KEY_SALT:-sgate_api_32bytes_min_change_in_production}
      WEBHOOK_SIGNATURE_SALT: ${WEBHOOK_SIGNATURE_SALT:-sgate_wh_32bytes_min_change_in_production}
      JWT_SECRET: ${JWT_SECRET:-dev-sgate-jwt-secret-change-in-production}
      STACKS_NETWORK: ${STACKS_NETWORK:-testnet}
      HIRO_API_BASE: ${HIRO_API_BASE:-https://api.testnet.hiro.so}
      SBTC_ASSET_IDENTIFIER: ${SBTC_ASSET_IDENTIFIER:-ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-token::sbtc}
      GATEWAY_ADDRESS: ${GATEWAY_ADDRESS:-ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM}
      API_BASE_URL: ${API_BASE_URL:-http://localhost:4000}
      CHECKOUT_BASE_URL: ${CHECKOUT_BASE_URL:-http://localhost:3000}
      REQUIRED_CONFIRMATIONS: ${REQUIRED_CONFIRMATIONS:-1}
      RATE_LIMIT_ENABLED: "true"
      ENABLE_METRICS: "false"
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      TRUST_PROXY: "1"
    ports:
      - "4000:4000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - api_logs:/app/logs
      - api_tmp:/app/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - sgate-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"

  # Web Dashboard
  web:
    build:
      context: .
      dockerfile: ./infra/Dockerfile.dashboard.simple
    image: sgate/web:${VERSION:-latest}
    container_name: sgate-web-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_BASE_URL: ${API_BASE_URL:-http://localhost:4000}
    ports:
      - "9024:3000"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - sgate-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"

  # Nginx Reverse Proxy (Optional - for production SSL/routing)
  nginx:
    image: nginx:alpine
    container_name: sgate-nginx-prod
    restart: unless-stopped
    ports:
      - "9025:80"
      - "9026:443"
    volumes:
      - ./infra/nginx/nginx.simple.conf:/etc/nginx/nginx.conf:ro
      - ./infra/ssl:/etc/ssl/certs:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      - api
      - web
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - sgate-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "3"
    profiles:
      - nginx

volumes:
  postgres_data:
    driver: local
  postgres_logs:
    driver: local
  redis_data:
    driver: local
  redis_logs:
    driver: local
  api_logs:
    driver: local
  api_tmp:
    driver: local
  nginx_logs:
    driver: local

networks:
  sgate-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

# Production deployment commands:
# 1. Create .env file with production values
# 2. docker-compose -f docker-compose.production.clean.yml build
# 3. docker-compose -f docker-compose.production.clean.yml up -d
# 4. docker-compose -f docker-compose.production.clean.yml logs -f api
# 
# To include nginx: 
# docker-compose -f docker-compose.production.clean.yml --profile nginx up -d